import { type AccountInfo, type IPublicClientApplication, InteractionRequiredAuthError } from "@azure/msal-browser";
import { afterEach, describe, expect, it, vi } from "vitest";
import { registerApiCheckIn } from "./api-check-in";
const id = "a4444444-4444-4444-8444-444444444444";
const saved = { id, registrationId: id, checkedInAt: "2026-09-24T18:00:00.000Z", source: "manual" };
function setup() {
  const token = vi.fn().mockResolvedValue({ accessToken: "secret" });
  const fetcher = vi.fn().mockResolvedValue(new Response(JSON.stringify({ status: "accepted", checkIn: saved }), { status: 201 }));
  vi.stubGlobal("fetch", fetcher);
  return { token, fetcher, options: { instance: { acquireTokenSilent: token } as unknown as IPublicClientApplication,
    account: { homeAccountId: "selected" } as AccountInfo, apiScope: "scope", apiUrl: "https://api.example.com/prefix", eventId: id.toUpperCase(), code: " oe1_Exact_Code " } };
}
afterEach(() => { vi.unstubAllGlobals(); vi.useRealTimers(); });
describe("manual check-in client", () => {
  it("sends exact code with verified account, no-store and fixed manual source", async () => {
    const s=setup(); expect(await registerApiCheckIn(s.options)).toEqual({status:"accepted",checkIn:saved});
    expect(s.token).toHaveBeenCalledExactlyOnceWith({account:s.options.account,scopes:["scope"]});
    expect(s.fetcher).toHaveBeenCalledExactlyOnceWith(`https://api.example.com/prefix/api/v1/events/${id}/check-ins`,expect.objectContaining({method:"POST",body:JSON.stringify({code:s.options.code,source:"manual"}),cache:"no-store",credentials:"omit",redirect:"error",headers:{Authorization:"Bearer secret",Accept:"application/json","Content-Type":"application/json"}}));
  });
  it.each(["bad","http://remote.example","https://u:p@example.com","https://example.com?q=x","https://example.com#x"])("rejects unsafe URL %s",async apiUrl=>{const s=setup();await expect(registerApiCheckIn({...s.options,apiUrl})).rejects.toMatchObject({kind:"configuration"});expect(s.token).not.toHaveBeenCalled();});
  it.each(["","x".repeat(257)])("rejects invalid code length %#",async code=>{const s=setup();await expect(registerApiCheckIn({...s.options,code})).rejects.toMatchObject({kind:"validation"});expect(s.fetcher).not.toHaveBeenCalled();});
  it("rejects invalid ID and empty scope before token",async()=>{const s=setup();await expect(registerApiCheckIn({...s.options,eventId:"../bad"})).rejects.toMatchObject({kind:"validation"});await expect(registerApiCheckIn({...s.options,apiScope:" "})).rejects.toMatchObject({kind:"configuration"});expect(s.token).not.toHaveBeenCalled();});
  it("snapshots code before awaiting token",async()=>{const s=setup();s.token.mockImplementation(async()=>{s.options.code="changed";return{accessToken:"secret"};});await registerApiCheckIn(s.options);expect(s.fetcher.mock.calls[0][1].body).toContain(" oe1_Exact_Code ");});
  it.each(["manual","qr"])("accepts duplicate preserving original source %s",async source=>{const s=setup();s.fetcher.mockResolvedValue(new Response(JSON.stringify({status:"duplicate",checkIn:{...saved,source}}),{status:409}));expect(await registerApiCheckIn(s.options)).toEqual({status:"duplicate",checkIn:{...saved,source}});});
  it("distinguishes invalid from inaccessible event",async()=>{const s=setup();s.fetcher.mockResolvedValueOnce(new Response('{"status":"invalid"}',{status:404})).mockResolvedValueOnce(new Response('{"code":"EVENT_NOT_FOUND"}',{status:404}));expect(await registerApiCheckIn(s.options)).toEqual({status:"invalid"});await expect(registerApiCheckIn(s.options)).rejects.toMatchObject({kind:"not_found"});});
  it("distinguishes closed event from duplicate",async()=>{const s=setup();s.fetcher.mockResolvedValue(new Response('{"code":"CHECK_IN_NOT_ALLOWED"}',{status:409}));await expect(registerApiCheckIn(s.options)).rejects.toMatchObject({kind:"not_active"});});
  it.each([[400,"validation"],[413,"validation"],[401,"unauthorized"],[403,"forbidden"],[500,"uncertain"],[200,"uncertain"],[415,"uncertain"]])("maps status %s without retry or leaking error",async(status,kind)=>{const s=setup();s.fetcher.mockResolvedValue(new Response('{"message":"private"}',{status:Number(status)}));await expect(registerApiCheckIn(s.options)).rejects.toMatchObject({kind});expect(s.fetcher).toHaveBeenCalledTimes(1);});
  it.each([{id:"bad"},{registrationId:"bad"},{checkedInAt:"yesterday"},{checkedInAt:"2026-02-30T12:00:00.000Z"},{checkedInAt:"2026-09-24T18:00:00+00:00"},{source:"camera"},{source:"qr"}])("rejects malformed accepted record %#",async change=>{const s=setup();s.fetcher.mockResolvedValue(new Response(JSON.stringify({status:"accepted",checkIn:{...saved,...change}}),{status:201}));await expect(registerApiCheckIn(s.options)).rejects.toMatchObject({kind:"uncertain"});});
  it.each([[201,{status:"duplicate",checkIn:saved}],[409,{status:"accepted",checkIn:saved}],[404,{status:"invalid",token:"private"}],[409,{status:"duplicate"}],[404,{}],[201,null]])("rejects mismatched contract %#",async(status,body)=>{const s=setup();s.fetcher.mockResolvedValue(new Response(JSON.stringify(body),{status:Number(status)}));await expect(registerApiCheckIn(s.options)).rejects.toMatchObject({kind:"uncertain"});});
  it("projects only permitted fields",async()=>{const s=setup();s.fetcher.mockResolvedValue(new Response(JSON.stringify({status:"accepted",checkIn:{...saved,performedBy:"private"},token:"private"}),{status:201}));expect(await registerApiCheckIn(s.options)).toEqual({status:"accepted",checkIn:saved});});
  it.each(["interaction_required","authentication"])("handles token error %s",async kind=>{const s=setup();s.token.mockRejectedValue(kind==="interaction_required"?new InteractionRequiredAuthError("interaction_required","Required"):new Error("private"));await expect(registerApiCheckIn(s.options)).rejects.toMatchObject({kind});expect(s.fetcher).not.toHaveBeenCalled();});
  it("rejects empty token",async()=>{const s=setup();s.token.mockResolvedValue({accessToken:" "});await expect(registerApiCheckIn(s.options)).rejects.toMatchObject({kind:"authentication"});expect(s.fetcher).not.toHaveBeenCalled();});
  it("does not send after account changes during token acquisition",async()=>{const s=setup();let current=true;s.token.mockImplementation(async()=>{current=false;return{accessToken:"secret"};});await expect(registerApiCheckIn({...s.options,isCurrent:()=>current})).rejects.toMatchObject({kind:"cancelled"});expect(s.fetcher).not.toHaveBeenCalled();});
  it("rejects pre-aborted requests and late responses",async()=>{const s=setup();const c=new AbortController();c.abort();await expect(registerApiCheckIn({...s.options,signal:c.signal})).rejects.toMatchObject({kind:"cancelled"});expect(s.token).not.toHaveBeenCalled();const late=new AbortController();s.fetcher.mockImplementation(async()=>{late.abort();return new Response(JSON.stringify({status:"accepted",checkIn:saved}),{status:201});});await expect(registerApiCheckIn({...s.options,signal:late.signal})).rejects.toMatchObject({kind:"cancelled"});});
  it("treats network and malformed JSON as uncertain",async()=>{const s=setup();s.fetcher.mockRejectedValueOnce(new Error("private")).mockResolvedValueOnce(new Response("{",{status:201}));for(let n=0;n<2;n++)await expect(registerApiCheckIn(s.options)).rejects.toMatchObject({kind:"uncertain"});expect(s.fetcher).toHaveBeenCalledTimes(2);});
  it("times out without retry and clears timer",async()=>{vi.useFakeTimers();const s=setup();s.fetcher.mockImplementation((_url,init:RequestInit)=>new Promise((_resolve,reject)=>{init.signal?.addEventListener("abort",()=>reject(new Error("timeout")));}));const result=expect(registerApiCheckIn(s.options)).rejects.toMatchObject({kind:"uncertain"});await vi.advanceTimersByTimeAsync(15000);await result;expect(s.fetcher).toHaveBeenCalledTimes(1);expect(vi.getTimerCount()).toBe(0);});
});

describe("camera check-in source", () => {
  it("sends and validates qr success",async()=>{const s=setup();s.fetcher.mockResolvedValue(new Response(JSON.stringify({status:"accepted",checkIn:{...saved,source:"qr"}}),{status:201}));expect(await registerApiCheckIn({...s.options,source:"qr"})).toEqual({status:"accepted",checkIn:{...saved,source:"qr"}});expect(s.fetcher.mock.calls[0][1].body).toBe(JSON.stringify({code:s.options.code,source:"qr"}));});
  it("rejects accepted manual source for a qr request",async()=>{const s=setup();await expect(registerApiCheckIn({...s.options,source:"qr"})).rejects.toMatchObject({kind:"uncertain"});});
  it.each(["manual","qr"])("preserves duplicate origin %s after a qr request",async source=>{const s=setup();s.fetcher.mockResolvedValue(new Response(JSON.stringify({status:"duplicate",checkIn:{...saved,source}}),{status:409}));expect(await registerApiCheckIn({...s.options,source:"qr"})).toEqual({status:"duplicate",checkIn:{...saved,source}});});
  it.each(["camera","",null])("rejects unknown origin %# before token",async source=>{const s=setup();await expect(registerApiCheckIn({...s.options,source:source as "qr"})).rejects.toMatchObject({kind:"validation"});expect(s.token).not.toHaveBeenCalled();});
  it("captures source before awaiting token",async()=>{const s=setup();const options={...s.options,source:"qr" as "qr"|"manual"};s.token.mockImplementation(async()=>{options.source="manual";return{accessToken:"secret"};});s.fetcher.mockResolvedValue(new Response(JSON.stringify({status:"accepted",checkIn:{...saved,source:"qr"}}),{status:201}));await registerApiCheckIn(options);expect(s.fetcher.mock.calls[0][1].body).toBe(JSON.stringify({code:s.options.code,source:"qr"}));});
});
