// @vitest-environment jsdom
import { act, cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { afterEach, expect, it, vi } from "vitest";
import AttendanceSummary from "./AttendanceSummary";
import { EventQueryError } from "./event-query-error";
const id="a4444444-4444-4444-8444-444444444444";
const data={eventId:id,registered:6,confirmed:4,cancelled:2,checkedIn:3,cancelledCheckedIn:1,pending:2,observedAt:"2026-09-26T21:00:00.000Z"};
function pending<T>(){let resolve!:(v:T)=>void;const promise=new Promise<T>(r=>{resolve=r;});return{promise,resolve};}
function props(){return{eventId:id,timezone:"America/Lima",load:vi.fn().mockResolvedValue(data),onFailure:vi.fn()};}
afterEach(cleanup);
it("loads real counts, history and event-zone time",async()=>{const p=props();render(<AttendanceSummary {...p}/>);await screen.findByText("4 confirmadas · 2 canceladas");expect(screen.getByText("1 con inscripción cancelada; se conserva su ingreso")).toBeTruthy();expect(screen.getByText(/Consulta realizada:/).textContent).toContain("16:00:00");expect(p.load).toHaveBeenCalledWith(id,expect.any(AbortSignal));expect(screen.queryByText(/%/)).toBeNull();});
it("clears old counts during refresh and never replaces failure with zeros",async()=>{const p=props();render(<AttendanceSummary {...p}/>);await screen.findByText("Registrados");const d=pending<typeof data>();p.load.mockReturnValue(d.promise);fireEvent.click(screen.getByText("Actualizar métricas"));expect(screen.queryByText("Registrados")).toBeNull();fireEvent.click(screen.getByText("Actualizar métricas"));expect(p.load).toHaveBeenCalledTimes(2);await act(async()=>d.resolve({...data,pending:99}));expect(await screen.findByRole("alert")).toBeTruthy();expect(screen.queryByText("Registrados")).toBeNull();p.load.mockResolvedValue(data);fireEvent.click(screen.getByText("Actualizar métricas"));await screen.findByText("Registrados");});
it("does not reload merely because parent renders",async()=>{const p=props();const view=render(<AttendanceSummary {...p}/>);await screen.findByText("Registrados");view.rerender(<AttendanceSummary {...p} load={vi.fn().mockResolvedValue(data)}/>);await act(async()=>{});expect(p.load).toHaveBeenCalledTimes(1);});
it("discards previous event response and aborts when unmounted",async()=>{const p=props();const old=pending<typeof data>();p.load.mockReturnValueOnce(old.promise);const view=render(<AttendanceSummary {...p}/>);const signal=p.load.mock.calls[0][1] as AbortSignal;const second={...data,eventId:"b4444444-4444-4444-8444-444444444444",registered:0,confirmed:0,cancelled:0,checkedIn:0,cancelledCheckedIn:0,pending:0};p.load.mockResolvedValue(second);view.rerender(<AttendanceSummary {...p} eventId={second.eventId}/>);await screen.findByText("0 confirmadas · 0 canceladas");await act(async()=>old.resolve(data));expect(signal.aborted).toBe(true);expect(screen.queryByText("4 confirmadas · 2 canceladas")).toBeNull();view.unmount();expect((p.load.mock.calls[1][1] as AbortSignal).aborted).toBe(false);});
it("aborts active read on exit",()=>{const p=props();p.load.mockReturnValue(new Promise(()=>{}));const v=render(<AttendanceSummary {...p}/>);const signal=p.load.mock.calls[0][1] as AbortSignal;v.unmount();expect(signal.aborted).toBe(true);});
it.each(["unauthorized","forbidden","not_found","interaction_required","authentication"] as const)("hides values and propagates %s",async kind=>{const p=props();p.load.mockRejectedValue(new EventQueryError(kind));render(<AttendanceSummary {...p}/>);await waitFor(()=>expect(p.onFailure).toHaveBeenCalledWith(expect.objectContaining({kind})));expect(screen.queryByText("Registrados")).toBeNull();expect((screen.getByText("Actualizar métricas") as HTMLButtonElement).disabled).toBe(true);});
