// @vitest-environment jsdom
import { act, cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { afterEach, describe, expect, it, vi } from "vitest";
import OperatorEvents from "./OperatorEvents";
import { CheckInError } from "./check-in-error";
import type { CheckInResult } from "./api-check-in";
const event={id:"a4444444-4444-4444-8444-444444444444",name:"Encuentro",startsAt:"2027-08-27T14:00:00.000Z",endsAt:"2027-08-27T22:00:00.000Z",timezone:"America/Lima",location:"Lima",status:"active" as const};
const accepted:CheckInResult={status:"accepted",checkIn:{id:event.id,registrationId:event.id,checkedInAt:"2026-09-24T18:00:00.000Z",source:"manual"}};
function setup(status:string="active") {const props={accountKey:"one",enabled:true,loadPage:vi.fn().mockResolvedValue({items:[event],nextCursor:null}),loadDetail:vi.fn().mockResolvedValue({...event,status}),searchPage:vi.fn().mockResolvedValue({items:[],nextCursor:null}),submitCheckIn:vi.fn().mockResolvedValue(accepted),onAccessInvalidated:vi.fn()};return{props,...render(<OperatorEvents {...props}/>)};}
async function select(){fireEvent.click(screen.getByText("Cargar eventos asignados"));fireEvent.click(await screen.findByText("Seleccionar Encuentro"));await screen.findByLabelText("Nombre o correo del inscrito");}
function send(code="exact-code "){fireEvent.change(screen.getByLabelText("Código de la credencial"),{target:{value:code}});fireEvent.click(screen.getByRole("button",{name:"Registrar ingreso"}));}
afterEach(cleanup);
describe("operator check-in view",()=>{
  it("sends only explicitly and clears code after success",async()=>{const s=setup();await select();expect(s.props.submitCheckIn).not.toHaveBeenCalled();send();await screen.findByText("Ingreso registrado correctamente.");expect(s.props.submitCheckIn).toHaveBeenCalledExactlyOnceWith(event.id,"exact-code ",expect.any(AbortSignal),"manual");expect((screen.getByLabelText("Código de la credencial") as HTMLInputElement).value).toBe("");expect(document.activeElement).toBe(screen.getByLabelText("Código de la credencial"));});
  it.each(["draft","closed","cancelled"])("offers no check-in for %s",async status=>{setup(status);await select();expect(screen.queryByLabelText("Código de la credencial")).toBeNull();});
  it.each(["invalid","duplicate"] as const)("shows %s and clears secret",async status=>{const s=setup();s.props.submitCheckIn.mockResolvedValue(status==="invalid"?{status}:{...accepted,status});await select();send();await screen.findByText(status==="invalid"?"Código no válido para este evento.":"Esta credencial ya tiene un ingreso registrado. No se creó otro ingreso.");expect((screen.getByLabelText("Código de la credencial") as HTMLInputElement).value).toBe("");});
  it("rejects empty code and clears explicitly",async()=>{const s=setup();await select();fireEvent.click(screen.getByRole("button",{name:"Registrar ingreso"}));expect(s.props.submitCheckIn).not.toHaveBeenCalled();expect(screen.getByRole("alert").textContent).toContain("256");fireEvent.change(screen.getByLabelText("Código de la credencial"),{target:{value:"secret"}});fireEvent.click(screen.getByText("Limpiar código"));expect((screen.getByLabelText("Código de la credencial") as HTMLInputElement).value).toBe("");});
  it("blocks double submit including Enter",async()=>{const s=setup();let resolve!:(v:CheckInResult)=>void;s.props.submitCheckIn.mockReturnValue(new Promise(r=>{resolve=r;}));await select();send();fireEvent.submit(screen.getByLabelText("Código de la credencial").closest("form")!);expect(s.props.submitCheckIn).toHaveBeenCalledTimes(1);await act(async()=>resolve(accepted));});
  it("keeps uncertain code only until explicit retry or clear",async()=>{const s=setup();s.props.submitCheckIn.mockRejectedValueOnce(new CheckInError("uncertain")).mockResolvedValueOnce({...accepted,status:"duplicate"});await select();send();await screen.findByRole("alert");expect(s.props.submitCheckIn).toHaveBeenCalledTimes(1);expect((screen.getByLabelText("Código de la credencial") as HTMLInputElement).value).toBe("exact-code ");fireEvent.click(screen.getByRole("button",{name:"Registrar ingreso"}));await screen.findByText(/No se creó otro ingreso/);expect(s.props.submitCheckIn).toHaveBeenCalledTimes(2);});
  it.each(["authentication","interaction_required","unauthorized","forbidden"] as const)("invalidates access for %s",async kind=>{const s=setup();s.props.submitCheckIn.mockRejectedValue(new CheckInError(kind));await select();send();await waitFor(()=>expect(s.props.onAccessInvalidated).toHaveBeenCalledOnce());expect(screen.queryByLabelText("Código de la credencial")).toBeNull();});
  it("removes inaccessible event",async()=>{const s=setup();s.props.submitCheckIn.mockRejectedValue(new CheckInError("not_found"));await select();send();await screen.findByText("Cargar eventos asignados");expect(screen.queryByLabelText("Código de la credencial")).toBeNull();expect(s.props.onAccessInvalidated).not.toHaveBeenCalled();});
  it("requires fresh detail after inactive rejection",async()=>{const s=setup();s.props.submitCheckIn.mockRejectedValue(new CheckInError("not_active"));await select();send();await screen.findByText("Consultar estado actual");expect(screen.queryByLabelText("Código de la credencial")).toBeNull();s.props.loadDetail.mockResolvedValue({...event,status:"closed"});fireEvent.click(screen.getByText("Consultar estado actual"));await screen.findByText("Lima · Cerrado");expect(screen.queryByLabelText("Código de la credencial")).toBeNull();});
  it.each(["back","account","disabled","unmount"])("aborts and ignores late completion on %s",async action=>{const s=setup();let resolve!:(v:CheckInResult)=>void;s.props.submitCheckIn.mockReturnValue(new Promise(r=>{resolve=r;}));await select();send();const signal=s.props.submitCheckIn.mock.calls[0][2] as AbortSignal;
    if(action==="back")fireEvent.click(screen.getByText("Volver a eventos asignados"));if(action==="account")s.rerender(<OperatorEvents {...s.props} accountKey="two"/>);if(action==="disabled")s.rerender(<OperatorEvents {...s.props} enabled={false}/>);if(action==="unmount")s.unmount();expect(signal.aborted).toBe(true);await act(async()=>resolve(accepted));expect(screen.queryByText("Ingreso registrado correctamente.")).toBeNull();});
  it("reopening starts with fresh detail and empty code",async()=>{const s=setup();await select();send();await screen.findByText("Ingreso registrado correctamente.");fireEvent.click(screen.getByText("Volver a eventos asignados"));fireEvent.click(screen.getByText("Seleccionar Encuentro"));await screen.findByLabelText("Código de la credencial");expect(s.props.loadDetail).toHaveBeenCalledTimes(2);expect(screen.queryByText("Ingreso registrado correctamente.")).toBeNull();});
});
