// @vitest-environment jsdom
import { act, cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import OperatorCheckIn from "./OperatorCheckIn";
import { startQrCamera } from "./qr-camera";
import { CheckInError } from "./check-in-error";
vi.mock("./qr-camera", async importOriginal=>({...await importOriginal<typeof import("./qr-camera")>(),startQrCamera:vi.fn()}));
const code="oe1_"+"A".repeat(43);
const stop=vi.fn();
function setup(){const props={eventId:"event",timezone:"America/Lima",submit:vi.fn().mockResolvedValue({status:"invalid"}),onFailure:vi.fn()};return{props,...render(<OperatorCheckIn {...props}/>)};}
function scan(){fireEvent.click(screen.getByText("Iniciar cámara"));act(()=>vi.mocked(startQrCamera).mock.calls.at(-1)![1](code));}
beforeEach(()=>{vi.mocked(startQrCamera).mockReset().mockReturnValue(stop);stop.mockReset();});afterEach(cleanup);
describe("camera to explicit check-in",()=>{
  it("never starts on mount and never submits on detection",()=>{const s=setup();expect(startQrCamera).not.toHaveBeenCalled();scan();expect(s.props.submit).not.toHaveBeenCalled();expect(screen.getByText("QR leído. Pulsa Registrar ingreso para confirmar.")).toBeTruthy();expect((screen.getByLabelText("Código de la credencial") as HTMLInputElement).value).toBe(code);});
  it("confirms a scanned code with qr source and clears it",async()=>{const s=setup();scan();fireEvent.click(screen.getByRole("button",{name:"Registrar ingreso"}));await screen.findByText("Código no válido para este evento.");expect(s.props.submit).toHaveBeenCalledExactlyOnceWith("event",code,expect.any(AbortSignal),"qr");expect(screen.queryByText(/QR leído/)).toBeNull();});
  it("editing a read switches source to manual",async()=>{const s=setup();scan();fireEvent.change(screen.getByLabelText("Código de la credencial"),{target:{value:code+" "}});fireEvent.click(screen.getByRole("button",{name:"Registrar ingreso"}));await screen.findByText("Código no válido para este evento.");expect(s.props.submit).toHaveBeenCalledWith("event",code+" ",expect.any(AbortSignal),"manual");});
  it("blocks manual submit and editing during capture then restores them",()=>{const s=setup();fireEvent.change(screen.getByLabelText("Código de la credencial"),{target:{value:"manual"}});fireEvent.click(screen.getByText("Iniciar cámara"));expect((screen.getByLabelText("Código de la credencial") as HTMLInputElement).disabled).toBe(true);fireEvent.submit(screen.getByLabelText("Código de la credencial").closest("form")!);expect(s.props.submit).not.toHaveBeenCalled();fireEvent.click(screen.getByText("Detener cámara"));expect(stop).toHaveBeenCalledOnce();expect((screen.getByLabelText("Código de la credencial") as HTMLInputElement).disabled).toBe(false);});
  it("does not acquire twice on double click",()=>{setup();const start=screen.getByText("Iniciar cámara");fireEvent.click(start);fireEvent.click(start);expect(startQrCamera).toHaveBeenCalledTimes(1);});
  it("stops camera on unmount",()=>{const s=setup();fireEvent.click(screen.getByText("Iniciar cámara"));s.unmount();expect(stop).toHaveBeenCalledOnce();});
  it("shows camera failure while manual input remains usable",async()=>{const s=setup();fireEvent.click(screen.getByText("Iniciar cámara"));act(()=>vi.mocked(startQrCamera).mock.calls[0][2]("permission"));expect(screen.getByRole("alert").textContent).toContain("permiso");fireEvent.change(screen.getByLabelText("Código de la credencial"),{target:{value:"manual"}});fireEvent.click(screen.getByRole("button",{name:"Registrar ingreso"}));await screen.findByText("Código no válido para este evento.");expect(s.props.submit).toHaveBeenCalledWith("event","manual",expect.any(AbortSignal),"manual");});
  it("retains qr origin for an explicit uncertain retry",async()=>{const s=setup();s.props.submit.mockRejectedValueOnce(new CheckInError("uncertain"));scan();fireEvent.click(screen.getByRole("button",{name:"Registrar ingreso"}));await screen.findByRole("alert");expect(s.props.submit).toHaveBeenCalledTimes(1);fireEvent.click(screen.getByRole("button",{name:"Registrar ingreso"}));await screen.findByText("Código no válido para este evento.");expect(s.props.submit).toHaveBeenLastCalledWith("event",code,expect.any(AbortSignal),"qr");});
  it("disables camera while waiting for HTTP response",async()=>{const s=setup();let resolve!:(v:unknown)=>void;s.props.submit.mockReturnValue(new Promise(r=>{resolve=r;}));scan();fireEvent.click(screen.getByRole("button",{name:"Registrar ingreso"}));expect((screen.getByText("Iniciar cámara") as HTMLButtonElement).disabled).toBe(true);await act(async()=>resolve({status:"invalid"}));await waitFor(()=>expect((screen.getByText("Iniciar cámara") as HTMLButtonElement).disabled).toBe(false));});
  it("clears captured value explicitly without a request",()=>{const s=setup();scan();fireEvent.click(screen.getByText("Limpiar código"));expect((screen.getByLabelText("Código de la credencial") as HTMLInputElement).value).toBe("");expect(screen.queryByText(/QR leído/)).toBeNull();expect(s.props.submit).not.toHaveBeenCalled();});
});
