// @vitest-environment jsdom
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import jsQR from "jsqr";
import { startQrCamera } from "./qr-camera";
vi.mock("jsqr", () => ({ default: vi.fn() }));
const code = "oe1_" + "A".repeat(43);
function deferred<T>() { let resolve!: (v:T)=>void; let reject!: (e:unknown)=>void; const promise=new Promise<T>((a,b)=>{resolve=a;reject=b;});return{resolve,reject,promise}; }
function setup() {
  const track = Object.assign(new EventTarget(), { stop:vi.fn(),readyState:"live" });
  const stream = {getTracks:()=>[track],getVideoTracks:()=>[track]} as unknown as MediaStream;
  const acquire = vi.fn().mockResolvedValue(stream); vi.stubGlobal("navigator", {mediaDevices:{getUserMedia:acquire}});
  const video=document.createElement("video");Object.defineProperties(video,{videoWidth:{value:1280},videoHeight:{value:720},readyState:{value:4}});
  const read=vi.fn();const error=vi.fn();return{track,stream,acquire,video,read,error};
}
async function flush(){for(let i=0;i<8;i++)await Promise.resolve();}
beforeEach(()=>{
  vi.useFakeTimers();vi.stubGlobal("isSecureContext",true);vi.spyOn(document,"hidden","get").mockReturnValue(false);
  vi.spyOn(HTMLMediaElement.prototype,"play").mockResolvedValue();vi.spyOn(HTMLMediaElement.prototype,"pause").mockImplementation(()=>{});
  vi.spyOn(HTMLCanvasElement.prototype,"getContext").mockReturnValue({drawImage:vi.fn(),getImageData:vi.fn().mockReturnValue({data:new Uint8ClampedArray(16),width:2,height:2})} as unknown as CanvasRenderingContext2D);
  vi.mocked(jsQR).mockReset().mockReturnValue(null);
});
afterEach(()=>{vi.restoreAllMocks();vi.unstubAllGlobals();vi.useRealTimers();});
describe("camera lifetime",()=>{
  it("requests video only, decodes once, stops tracks and releases preview",async()=>{const s=setup();vi.mocked(jsQR).mockReturnValue({data:code} as NonNullable<ReturnType<typeof jsQR>>);startQrCamera(s.video,s.read,s.error);await flush();expect(s.acquire).toHaveBeenCalledExactlyOnceWith({audio:false,video:{facingMode:{ideal:"environment"},width:{ideal:1280},height:{ideal:720}}});expect(s.read).toHaveBeenCalledExactlyOnceWith(code);expect(s.track.stop).toHaveBeenCalledOnce();expect(s.video.srcObject).toBeNull();expect(s.error).not.toHaveBeenCalled();await vi.advanceTimersByTimeAsync(1000);expect(s.read).toHaveBeenCalledTimes(1);expect(vi.getTimerCount()).toBe(0);});
  it.each(["insecure","unsupported","hidden"])("does not acquire when %s",async kind=>{const s=setup();if(kind==="insecure")vi.stubGlobal("isSecureContext",false);if(kind==="unsupported")vi.stubGlobal("navigator",{});if(kind==="hidden")vi.spyOn(document,"hidden","get").mockReturnValue(true);startQrCamera(s.video,s.read,s.error);await flush();expect(s.acquire).not.toHaveBeenCalled();expect(s.error).toHaveBeenCalledWith(kind);});
  it.each([["NotAllowedError","permission"],["SecurityError","permission"],["NotFoundError","missing"],["NotReadableError","unavailable"],["OverconstrainedError","unavailable"]])("maps %s without leaking error",async(name,kind)=>{const s=setup();s.acquire.mockRejectedValue(new DOMException("private-device",name));startQrCamera(s.video,s.read,s.error);await flush();expect(s.error).toHaveBeenCalledExactlyOnceWith(kind);expect(s.read).not.toHaveBeenCalled();});
  it("cancels before permission begins",async()=>{const s=setup();const stop=startQrCamera(s.video,s.read,s.error);stop();await flush();expect(s.acquire).not.toHaveBeenCalled();});
  it("releases a permission stream arriving after cancellation",async()=>{const s=setup();const late=deferred<MediaStream>();s.acquire.mockReturnValue(late.promise);const stop=startQrCamera(s.video,s.read,s.error);await flush();stop();late.resolve(s.stream);await flush();expect(s.track.stop).toHaveBeenCalledOnce();expect(s.read).not.toHaveBeenCalled();expect(s.error).not.toHaveBeenCalled();expect(s.video.srcObject).toBeUndefined();});
  it("ignores permission rejection after cancel",async()=>{const s=setup();const late=deferred<MediaStream>();s.acquire.mockReturnValue(late.promise);const stop=startQrCamera(s.video,s.read,s.error);await flush();stop();late.reject(new Error("private"));await flush();expect(s.error).not.toHaveBeenCalled();});
  it("old stream cannot replace a newly started preview",async()=>{const s=setup();const old=deferred<MediaStream>();s.acquire.mockReturnValueOnce(old.promise);const first=startQrCamera(s.video,s.read,s.error);await flush();first();const second=startQrCamera(s.video,s.read,s.error);await flush();const oldTrack={stop:vi.fn()};old.resolve({getTracks:()=>[oldTrack]} as unknown as MediaStream);await flush();expect(oldTrack.stop).toHaveBeenCalledOnce();expect(s.video.srcObject).toBe(s.stream);expect(s.track.stop).not.toHaveBeenCalled();second();});
  it.each(["reject","cancel"])("releases stream during pending playback: %s",async action=>{const s=setup();const play=deferred<void>();vi.mocked(s.video.play).mockReturnValue(play.promise);const stop=startQrCamera(s.video,s.read,s.error);await flush();if(action==="cancel"){stop();play.resolve();}else play.reject(new Error("private"));await flush();expect(s.track.stop).toHaveBeenCalledOnce();expect(s.video.srcObject).toBeNull();expect(s.read).not.toHaveBeenCalled();expect(s.error).toHaveBeenCalledTimes(action==="cancel"?0:1);});
  it("stops polling on cancel and can cancel twice",async()=>{const s=setup();const stop=startQrCamera(s.video,s.read,s.error);await flush();expect(vi.getTimerCount()).toBe(1);stop();stop();await vi.advanceTimersByTimeAsync(1000);expect(s.track.stop).toHaveBeenCalledOnce();expect(vi.getTimerCount()).toBe(0);expect(s.read).not.toHaveBeenCalled();});
  it.each(["scanning","permission"])("stops on hidden page during %s without auto-resume",async phase=>{const s=setup();const permission=deferred<MediaStream>();if(phase==="permission")s.acquire.mockReturnValue(permission.promise);startQrCamera(s.video,s.read,s.error);await flush();vi.spyOn(document,"hidden","get").mockReturnValue(true);document.dispatchEvent(new Event("visibilitychange"));if(phase==="permission")permission.resolve(s.stream);await flush();expect(s.track.stop).toHaveBeenCalledOnce();expect(s.error).toHaveBeenCalledExactlyOnceWith("hidden");vi.spyOn(document,"hidden","get").mockReturnValue(false);document.dispatchEvent(new Event("visibilitychange"));expect(s.acquire).toHaveBeenCalledTimes(1);expect(vi.getTimerCount()).toBe(0);});
  it("stops when the device disconnects",async()=>{const s=setup();startQrCamera(s.video,s.read,s.error);await flush();s.track.dispatchEvent(new Event("ended"));expect(s.error).toHaveBeenCalledExactlyOnceWith("unavailable");expect(s.track.stop).toHaveBeenCalledOnce();expect(vi.getTimerCount()).toBe(0);});
  it("rejects an already ended device",async()=>{const s=setup();s.track.readyState="ended";startQrCamera(s.video,s.read,s.error);await flush();expect(s.error).toHaveBeenCalledWith("missing");expect(s.track.stop).toHaveBeenCalledOnce();});
  it.each(["https://example.com","<script>secret</script>","",code+" ","oe1_"+"B".repeat(43)])("does not forward unexpected QR content %#",async data=>{const s=setup();vi.mocked(jsQR).mockReturnValue({data} as NonNullable<ReturnType<typeof jsQR>>);startQrCamera(s.video,s.read,s.error);await flush();expect(s.read).not.toHaveBeenCalled();expect(s.error).toHaveBeenCalledExactlyOnceWith("invalid");expect(s.track.stop).toHaveBeenCalledOnce();});
  it.each(["context","decoder"])("releases camera after %s failure",async stage=>{const s=setup();if(stage==="context")vi.mocked(HTMLCanvasElement.prototype.getContext).mockReturnValue(null);else vi.mocked(jsQR).mockImplementation(()=>{throw new Error("private-frame");});startQrCamera(s.video,s.read,s.error);await flush();expect(s.error).toHaveBeenCalledExactlyOnceWith("unavailable");expect(s.track.stop).toHaveBeenCalledOnce();});
});
